services:
  - type: web
    name: identifyou-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build && npx prisma generate
    startCommand: npm run dev
    envVars:
      - key: NODE_ENV
        value: development
      - key: DATABASE_URL
        sync: false
    autoDeploy: true
    branch: main